version: "3.3"

services:
  service:
    image: "registry.khitkabar.xyz:5443/${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}"
    container_name: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}"
    networks:
      - server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ops-${CI_COMMIT_BRANCH}.rule=Host(`ops-${CI_COMMIT_BRANCH}.khitkabar.xyz`) && PathPrefix(`${ROUTE}`)"
      - "traefik.http.routers.ops-${CI_COMMIT_BRANCH}.entrypoints=web"
      #- "traefik.http.services.traefik.loadbalancer.server.port=8000"

networks:
  server:
    external: true
